### ISSUE TITLE
Netlify-CLI not using NETLIFY_AUTH_TOKEN for authentication

### ISSUE THREAD

**Issue by chaudharykiran** [netlify/cli#1118]
**- Do you want to request a _feature_ or report a _bug_?**
Bug

**- What is the current behavior?**
```
$ netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
Logging into your Netlify account...
Opening https://app.netlify.com/authorize?response_type=ticket&ticket=ab6399435fc9fe8cf0801e4402865abc
---------------------------
Error: Unable to open browser automatically
Exited with code 3
```

**- If the current behaviour is a bug, please provide the steps to reproduce.**
```
jobs:
  build:
    name: FrontEndBuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: Install NetlifyCLI
        run: npm install -g netlify-cli@2.59.1
      - name: Deploy in Netlify
        run: yarn workspace @rsn/client deploy:prod
```
I am using deploy:prod script in my package.json file as below:
```
"deploy:prod": "netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
```
But when CI run it always yield error with Not able to open the browser.

**- What is the expected behaviour?**

Netlify Auth Token should be used for authentication.

**- Local Environment Information**
Github Actions CLI
