### ISSUE TITLE
"TypeError: uploadFiles is not a function" when deploying with v2.69.4

### ISSUE THREAD

**Issue by WIStudent** [netlify/cli#1640]
I use netlify-cli inside a Github Action workflow to deploy files to netlify after building them. The workflow looks similar to this (I omitted some building steps in between):
```yaml
name: CI
on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup node
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      # Caching npm
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node
      # Install netlify cli
      - run: npm install netlify-cli
      # Run build
      - run: npm run build
      # Deploy to netlify
      - run: npx netlify deploy --dir=target --prod --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SIDE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
```

This fails with `TypeError: uploadFiles is not a function`. When I install netlify-cli@2.69.3 instead, it works without error. I don't know if this is a general issue with v2.69.4 or limited to Github Actions.

**To Reproduce**

1. Run `npm install netlify-cli` inside a Github Action workflow
2. Run `npx netlify deploy --dir=target --prod --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN`
4. See that the CLI exits with error `TypeError: uploadFiles is not a function`

**CLI Output**

```
Run npx netlify deploy --dir=target --prod --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
  npx netlify deploy --dir=target --prod --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
  shell: /bin/bash -e {0}
  env:
    NETLIFY_SITE_ID: ***
    NETLIFY_AUTH_TOKEN: ***
Deploy path: <omitted>/target
Deploying to main site URL...
- Hashing files...
✔ Finished hashing 193 files
- CDN diffing files...
✔ CDN requesting 1 files
 ›   Warning: 
 ›   {}
 ›
    TypeError: uploadFiles is not a function
Error: Process completed with exit code 2.
```
