### ISSUE TITLE
Netlify Dev local redirects not working as intended

### ISSUE THREAD

**Issue by lukecurtis93** [netlify/cli#1681]
**Describe the bug**
Hi there,

I've followed the docs I believe and have an issue whereby my redirects work on netlify, using `_redirects` file, however when running `netlify dev` in the local repository, the redirect doesn't appear to work.

**To Reproduce**

Setup a redirects with the following (in public/_redirects)
```
# SPA
/api/* http://my.api.com/api:splat 200

/*    /index.html   200
```

When using axios to POST binary data (I'm using a vue SPA) to `localhost:8082/api/upload-media` (the port of my local development server) it does not correctly redirect and simply returns a 404

**Configuration**
```bash
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 69.27 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 7.0.14 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 2.57.0```
```
**Expected behavior**

I expect the redirect to work as intended when in local development

Apologies in advanced if this is incorrectly configured my end... I followed the instructions here https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file

**Comment by notpushkin** [comment]
I have a somewhat similar issue which might or might not be related. I'm using rewrite system to enable support for `index.xhtml` page. The following config does it for Netlify the service:

```toml
[[redirects]]
  from = "/*/"
  to = "/:splat/index.xhtml"
  status = 200
```

However, when running `netlify dev` locally it doesn't seem to work for the root directory (`/` → `/index.xhtml`). The following does the trick:

```toml
[[redirects]]
  from = "/"
  to = "/index.xhtml"
  status = 200

[[redirects]]
  from = "/*/"
  to = "/:splat/index.xhtml"
  status = 200
```
