### ISSUE TITLE
(REPOST)Redirects with country-specific condition are still ignored when running netlify dev with the -e flag

### ISSUE THREAD

**Issue by nonAlgebraic** [netlify/cli#1820]
**Describe the bug**

**NOTE:** this is a clone of #1786 , which was closed with a "fixed" comment by @calavera, but I am still able to reproduce the original bug.

When running `netlify dev` with the `-e` flag, if there is a redirection rule with a "Country" condition, then when the user makes a request that incldues the `nf_country` cookie set to that country's two-letter code (as documented [here](https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file)), the redirection rule is not applied.

**To Reproduce**

1. Clone this minimal reproduction repo: https://github.com/nonAlgebraic/netlify-cli-redirect-country-condition-bug-repro
2. Run `yarn install`
3. Run `yarn netlify dev -e`
4. When the browse window opens on http://localhost:9090/, it will 301 redirect to http://localhost:9090/us.html as stipulated by the **second** redirection rule that is configured in `netlify.toml`. when us.html loads, a script in it will set the `nf_country` cookie to the value "`CA`".
5. Navigate to http://localhost:9090/ again. Instead of being redirected to http://localhost:9090/canada.html as stipulated by the **first** conditional redirection rule in `netlify.toml`, you will be redirected to http://localhost:9090/us.html again, suggesting that the `nf_country` cookie is not respected by the server.

If you run `yarn netlify dev` without the `-e` flag, the problem goes away and step 5 above results in being redirected to http://localhost:9090/canada.html, suggesting that the `nf_country` cookie is respected by the server.

**Configuration**

`netlify.toml`:
```TOML
[dev]
  command = "yarn start"
  framework = "#custom"
  publish = "public"
  targetPort = 8080
  port = 9090

[[redirects]]
  from = "/"
  to = "/canada.html"
  status = 301
  force = true
  conditions = {Country = ["CA"]}

[[redirects]]
  from = "/"
  to = "/us.html"
  status = 301
  force = true
```
Output of `envinfo`:
```bash
System:
  OS: macOS 11.2.3
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 767.13 MB / 16.00 GB
  Shell: 3.2.57 - /bin/bash
Binaries:
  Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
  Yarn: 1.22.10 - ~/projects/netlify-cli-redirect-country-condition-bug-repro/node_modules/.bin/yarn
  npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Watchman: 4.9.0 - /usr/local/bin/watchman
npmPackages:
  netlify-cli: ^3.17.1 => 3.17.1
```

**Expected behavior**
Setting the `nf_country` cookie to a country code that is included in a conditional redirection rule with that country code in its `Country` condition array, that redirection rule should apply.
