### ISSUE TITLE
Site ID not picked up from netlify.toml

### ISSUE THREAD

**Issue by dstaley** [netlify/cli#197]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
`netlify deploy` with a `netlify.toml` in the root directory fails with the error `This folder isn't linked to a site yet`.

**- If the current behavior is a bug, please provide the steps to reproduce.** 
1. Create a `netlify.toml` file with Settings -> ID set to a valid site ID.
2. Run `netlify deploy`

**- What is the expected behavior?**
The site is deployed to the site ID specified in `netlify.toml`.

**- Please mention your node.js, and operating system version.**
Node v8.11.3
macOS 10.14.1

This is a regression compared to the Go CLI as running `netlifyctl deploy` works correctly.

**Comment by DavidWells** [comment]
Hey thanks for the report.

What does your `netlify.toml` look like?

**Comment by dstaley** [comment]
```toml
[Settings]
  ID = "30fc7629-818d-4127-9bd0-d79544654a4d"

[build]
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```
