### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] if publish direct already exists

### ISSUE THREAD

**Issue by unclejustin** [netlify/cli#2216]
**Describe the bug**

When running `ntl dev` in a project that already contains the publish directory the following error is thrown:

```sh
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Url.parse (url.js:160:3)
    at Object.urlParse [as parse] (url.js:155:13)
    at Object.common.setupOutgoing (/Users/username/.asdf/installs/nodejs/14.15.4/.npm/lib/node_modules/netlify-cli/node_modules/http-proxy/lib/http-proxy/common.js:87:12)
    at Array.stream (/Users/username/.asdf/installs/nodejs/14.15.4/.npm/lib/node_modules/netlify-cli/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:127:14)
    at ProxyServer.<anonymous> (/Users/username/.asdf/installs/nodejs/14.15.4/.npm/lib/node_modules/netlify-cli/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
    at Object.web (/Users/username/.asdf/installs/nodejs/14.15.4/.npm/lib/node_modules/netlify-cli/src/utils/proxy.js:331:20)
    at serveRedirect (/Users/username/.asdf/installs/nodejs/14.15.4/.npm/lib/node_modules/netlify-cli/src/utils/proxy.js:114:28)
    at ProxyServer.<anonymous> (/Users/username/.asdf/installs/nodejs/14.15.4/.npm/lib/node_modules/netlify-cli/src/utils/proxy.js:305:14)
    at ProxyServer.emit (/Users/username/.asdf/installs/nodejs/14.15.4/.npm/lib/node_modules/netlify-cli/node_modules/eventemitter3/index.js:183:35)
```

**To Reproduce**

1. Open project
2. Run `ntl build`
3. Run `ntl dev` 
4. Try to navigate to dev URL
5. Errors here
6. Delete the designated publish directory i.e. "dist"
7. Run `ntl dev` again
8. Try to navigate to dev URL
9. This time it will work

**Configuration**

```toml
[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev" # Command to start your dev server
  publish = "dist" # Folder with the static content for _redirect file
  targetPort = 3333
  framework = "#custom"
  autoLaunch = false
```

```bash
  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 3.13 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.asdf/installs/nodejs/14.15.4/bin/node
    Yarn: 1.22.5 - ~/.asdf/shims/yarn
    npm: 6.14.10 - ~/.asdf/installs/nodejs/14.15.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmGlobalPackages:
    netlify-cli: 3.21.8
```

**Expected behavior**

It shouldn't matter if the publish directory exists. Running `ntl dev` and navigating to the URL should still work.
