### ISSUE TITLE
[dev.environment] override not working

### ISSUE THREAD

**Issue by MentalGear** [netlify/cli#2306]
**Describe the bug**

[dev] command is overriding fine. But custom environment vars are not applied for the [dev.environment] block.

**To Reproduce**

1. add to your netlify.toml
```toml
[build.environment]
  APP_CONTEXT = 'production'

[dev]
   command = "yarn dev"
[dev.environment]
  APP_CONTEXT = 'development'
```
2. print the APP_CONTEXT somewhere in code
3. run netlift dev
4. APP_CONTEXT is still `production`

```toml
 # Settings in the [build] context are global and are applied to all contexts
 # unless otherwise overridden by more specific contexts.
[build]
  command = "yarn generate"
  publish = "dist"
  ignore = "git log -1 --pretty=%B | grep dependabot"
[build.environment]
  APP_CONTEXT = 'production'

# Serverless (Netlify) Functions
[functions]
  directory = "serverlessFunctions"
  node_bundler = "esbuild"

# these settings apply if the `netlify dev` command is used to run the app
[dev]
   command = "yarn dev"
   # port = 3000
[dev.environment]
  APP_CONTEXT = 'development'

```

```bash
  System:
    OS: macOS 10.15.7
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 1.29 GB / 40.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
```

**Expected behavior**

Dev vars override.
