### ISSUE TITLE
Redirects to absolute URLs include the port number of the development server

### ISSUE THREAD

**Issue by nonAlgebraic** [netlify/cli#2327]
When a redirect rule has a `to` value that is an absolute URL without a port number, but the `netlify dev` server is running on a non-80 port such that its `localhost` address does include a port number, requests that match that redirect rule are redirected to the `to` URL **with the dev server port number included**.

**To Reproduce**

1. Run `git clone git@github.com:nonAlgebraic/netlify-cli-redirect-port-bug-repro`
2. Navigate to the cloned repository
3. Run `yarn install`
3. Run `netlify dev -e`
4. See that navigating to `http://localhost:9090/` results in a redirection to `https://www.example.com:9090/`.

**Configuration**

Contents of `netlify.toml`:
```TOML
[dev]
  command = "yarn start"
  framework = "#custom"
  publish = "public"
  targetPort = 8080
  port = 9090
  autoLaunch = false

[[redirects]]
  from = "/"
  to = "https://www.example.com"
  status = 301
  force = true
```

Output of `envinfo`:
```bash
System:
  OS: macOS 11.3
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 321.68 MB / 16.00 GB
  Shell: 3.2.57 - /bin/bash
Binaries:
  Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
  Yarn: 1.22.10 - ~/projects/netlify-cli-redirect-port-bug-repro/node_modules/.bin/yarn
  npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Watchman: 4.9.0 - /usr/local/bin/watchman
npmPackages:
  netlify-cli: ^3.28.0 => 3.28.0
```

**Expected behavior**

The user is redirected to `https://www.example.com/` as configured, without a port number.
