### ISSUE TITLE
Deploy previews not using context

### ISSUE THREAD

**Issue by MentalGear** [netlify/cli#2571]
**Describe the bug**

Pull request previews don't trigger a context (branch)'s command.

**To Reproduce**

Auto pull request deploy-previews are activated on the 'stage' branch.

Given the following netlify file:

```toml
# #####################################
# GLOBAL
# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "dist"

# #####################################
# NETLIFY DEV
# these settings only apply if the `netlify dev` command is used to run the app
[dev]
   command = "yarn dev"
   # port = 3000
# [dev.environment] NOT implemented by netlify

# #####################################
# STAGE Branch
[context.stage]
  command = "yarn stage"
```

**Expected behavior**

Normally, when running the 'yarn stage' command generates a static site in the `/dist` folder.
However, that command is not executed when deploy-previews for pull requests on the 'stage' branch are triggered, no 'dist' folder is available and no mention of the command is in the logs.

**CLI Output**

```cli
1:43:10 PM:   Error message
1:43:10 PM:   Deploy did not succeed: Deploy directory 'dist' does not exist
1:43:10 PM: ​
```
