### ISSUE TITLE
Having trouble integrating Netlify cli into Continous Deployment

### ISSUE THREAD

**Issue by aldy97** [netlify/cli#3076]
**Describe the bug**

![image](https://user-images.githubusercontent.com/40585236/127934822-29ac0a7a-8808-4ad3-8293-bdf62db60a18.png)
I am required to mannually click on the link in order to authorize this operation of deployment.

**To Reproduce**

Push or merge to master branch

**Configuration**
- On Netlify UI, stopped auto deploy:
![image](https://user-images.githubusercontent.com/40585236/127935273-4fb44638-231a-4bba-81c3-e9733bd4f561.png)

- master.yml:
```
name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Build Site
        run: npm run build

      # Deploy the site with netlify-cli
      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=public --prod

```

- Had site id and auth token written in secrets:
![image](https://user-images.githubusercontent.com/40585236/127934980-6b751238-dd13-49bd-9fda-a7d7668dc8ce.png)

**Expected behavior**

Website should be auto-deployed with Netlify cli without human involvment. But even after manual work, the website is still not deployed.
