### ISSUE TITLE
`netlify dev` function not updating

### ISSUE THREAD

**Issue by mcansh** [netlify/cli#3374]
**Describe the bug**

**To Reproduce**

1. Run `git clone git@github.com:owner/repo-with-cli-bug.git`
2. Navigate to the cloned repository
3. Run `netlify dev` and `./build.cjs --watch`
4. make a change to `./src/index.js`
4. notice that the dist file (`netlify/functions/server/dist/index.cjs`) is updated and whats shown in the browser is not

**Configuration**

- If possible, please copy/paste below your `netlify.toml`.

```toml
[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  functions = "netlify/functions"
  publish = "public"
  port = 3000
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
```

- Please enter the following command in a terminal and copy/paste its output:

```bash
npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
```

```
  System:
    OS: macOS 12.0
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 786.18 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.n/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.24.0 - ~/.n/bin/npm
  npmGlobalPackages:
    netlify-cli: 6.9.9
```

**Expected behavior**

the require cache would be updated and show the latest changes

**CLI Output**

If applicable, add the CLI output to help explain your problem.

**Additional context**
