### ISSUE TITLE
Cannot authenticate in my CI/CD CircleCI workflow

### ISSUE THREAD

**Issue by mikirobles** [netlify/cli#353]
I'm trying to integrate netlify deploys to my CI/CD workflow in CircleCI but I am running into authentication issues.

I've set up the `NETLIFY_AUTH_TOKEN` env variable in the circleci project and i've also tried connecting to the container via SSH and setting it manually via `export NETLIFY_AUTH_TOKEN=XXXX`.

I've also tried using `netlify deploy --auth xxxx`.

This all results in:
```
Logging into your Netlify account...
Opening https://app.netlify.com/authorize?response_type=ticket&ticket=xxxx
---------------------------
Error: Unable to open browser automatically

Please open your browser & open the URL below to login:
https://app.netlify.com/authorize?response_type=ticket&ticket=xxxx
---------------------------
```

Why is this happening?

My project does not have netlify config files. What I want to do is create a new site for every PR.

This is the workflow:

```
  deploy-netlify-preview:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Set site name"
          command: site="EMPLOYERS-PR-${CIRCLE_PR_NUMBER}"
      - run:
          name: "Set Netlify Token env variable"
          command: export NETLIFY_AUTH_TOKEN=${NETLIFY_AUTH_TOKEN}
      - run:
          name: "Install Netlify CLI tools"
          command: sudo npm install -g netlify-cli
      - run:
          name: "Fetch sites from Netlify"
          command: sites="$(netlify sites:list)"
      - run:
          name: "Create site if it doesn't exist"
          command: |
            if [[ ! "$sites" =~ "$site" ]]
            then
              netlify sites:create --name "$site" -a ${NETLIFY_TEAM_SLUG}
            fi
      - run:
          name: "Deploy site"
          command: netlify deploy --prod -s "$site" --dir build
```

It actually hangs at "Fetch sites from Netlify" (stuck loading without error);
When connecting to the container via SSH and trying to deploy manually, login message occurrs. If I `printenv` I can see NETLIFY_AUTH_TOKEN is set properly.

Env:
- Node: v10
- Docker image: circleci/node:10
- netlify-cli/2.11.23 linux-x64 node-v10.16.0

**Comment by fool** [comment]
intention is that you'd use `netlify login` to get your auth setup, and check that auth into your repo where circle would use it.  Then you'd set a NETLIFY_AUTH_TOKEN and between the config saved on the filesave and the CLI seeing that value, authentication should be non-interactive.

**Comment by mikirobles** [comment]
@fool Sorry, I don't completely follow.
Is this what you mean?:

1. I use `netlify login` in my computer, this generates a `.netlify` folder in my home folder.
2. I (move?) that folder into my repo and check it
3. I create a Personal Token and set it as an env variable in CircleCI.

Im sure I got that wrong, but I just have a hard time understanding it.

**Comment by mikirobles** [comment]
As a temporary fix I just used the `netlifyctl` tool like this:

```yaml
  deploy-netlify-preview:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Download Netlify CLI tools"
          command: wget https://github.com/netlify/netlifyctl/releases/download/v0.4.0/netlifyctl-linux-amd64-0.4.0.tar.gz
      - run:
          name: "Unpack Netlify CLI tools"
          command: |
              tar -xzvf netlifyctl-linux-amd64-0.4.0.tar.gz
              ./netlifyctl version
      - run:
          name: "Deploy site"
          command: |
              pr_number=$(echo ${CI_PULL_REQUEST} | cut -d/ -f7)
              site_name="employers-pr-${pr_number}"
              sites="$(./netlifyctl sites -A $NETLIFY_AUTH_TOKEN)"
              echo "The site name is $site_name"
              echo "The sites we have are $sites"
              if [[ ! "$sites" =~ "$site_name" ]]
              then
                echo "Site doesn't exist, will create it now"
                echo "Creating site with name $site_name"
                ./netlifyctl site create -n "$site_name" -A $NETLIFY_AUTH_TOKEN
              fi
              yes n | ./netlifyctl deploy -n "$site_name" -b build -A $NETLIFY_AUTH_TOKEN || true
```

**Comment by DavidWells** [comment]
Hey @mikirobles 

Did you try a deploy command like so:

```
netlify deploy --prod --dir /your-dir --message "site deployed yay" --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
```

This should work or we have a regression on our hands

**Comment by DavidWells** [comment]
The current flow does this:

Check for auth https://github.com/netlify/cli/blob/master/src/commands/deploy.js#L23

Which calls https://github.com/netlify/cli-utils/blob/master/src/index.js#L80-L81

If no token found, it will try and pop open the browser. 

---

I'm curious to know if `command: export NETLIFY_AUTH_TOKEN=${NETLIFY_AUTH_TOKEN}` is setting a null value. 

Adding `echo $NETLIFY_AUTH_TOKEN` the build command should tell us

```
      - run:
          name: "Deploy site"
          command: echo $NETLIFY_AUTH_TOKEN && netlify deploy --prod -s "$site" --dir build
```

**Comment by mikirobles** [comment]
@DavidWells 
Theres a couple problems with that:
 1- I might not have a site id yet (if pull request was just created, the site id will be a new one)

 2- If I want to check if I have a site id for that PR, I'd have to run `netlify sites:list` which is stuck Loading (maybe an auth problem).
This is the log for that:
```
circleci@9bb24b754099:~/project/build$ DEBUG=* netlify sites:list
  @oclif/config reading core plugin /usr/local/lib/node_modules/netlify-cli +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/package.json +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/oclif.manifest.json +7ms
  @oclif/config:netlify-cli using manifest from /usr/local/lib/node_modules/netlify-cli/oclif.manifest.json +0ms
  @oclif/config reading user plugins pjson /home/circleci/.local/share/netlify-cli/package.json +0ms
  @oclif/config loadJSON /home/circleci/.local/share/netlify-cli/package.json +1ms
  @oclif/config loading plugins [ '@oclif/plugin-not-found',
  '@oclif/plugin-plugins',
  '@oclif/plugin-help',
  'netlify-dev-plugin' ] +1ms
  @oclif/config reading core plugin /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-not-found +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-not-found/package.json +3ms
  @oclif/config reading core plugin /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-plugins +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-plugins/package.json +0ms
  @oclif/config reading core plugin /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-help +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-help/package.json +0ms
  @oclif/config reading core plugin /usr/local/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/package.json +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-not-found/oclif.manifest.json +1ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-plugins/oclif.manifest.json +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/oclif.manifest.json +1ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-not-found/.oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-plugins using manifest from /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-plugins/oclif.manifest.json +0ms
  @oclif/config:netlify-dev-plugin using manifest from /usr/local/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-help using manifest from /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-not-found using manifest from /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-not-found/.oclif.manifest.json +0ms
  @oclif/config config done +5ms
  @oclif/config start init hook +1ms
  netlify:netlify-cli:hooks:init start /usr/local/lib/node_modules/netlify-cli/src/hooks/init +0ms
  netlify:netlify-cli:hooks:init done +31ms
  @oclif/config init hook done +246ms
  netlify init version: @oclif/command@1.5.14 argv: [ 'sites:list' ] +0ms
  @oclif/config runCommand sites:list [] +3ms
  @oclif/config:netlify-cli require /usr/local/lib/node_modules/netlify-cli/src/commands/sites/list.js +258ms
  @oclif/config start prerun hook +257ms
  @oclif/config prerun hook done +0ms
  netlify options: { userAgent: 'netlify/js-client',
  netlify   scheme: 'https',
  netlify   host: 'api.netlify.com',
  netlify   pathPrefix: '/api/v1' } +0ms
Loading your sites...
```


3- If I run the command you just said without a site id, I get asked if I want to link an existing site or create a new one. Either option tries to open a browser to log in even if my NETLIFY_AUTH_TOKEN is set.

4- `echo $NETLIFY_AUTH_TOKEN` prints auth token correctly. This is the same variable used with the `netlifyctl` flow and it's working fine there.

My ideas:
 - maybe NETLIFY_AUTH_TOKEN is only used on deploy and not for any other command?

**Comment by DavidWells** [comment]
The `--auth` flag isn't used on the `netlify sites:list` command https://github.com/netlify/cli/blob/master/src/commands/sites/list.js#L11

Is that `netlify sites:list` command returning a list of sites? (if so, the token is good and something else is happening here)

**Comment by mikirobles** [comment]
`netlify sites:list` is stuck on `Loading your sites...` .

**Comment by mikirobles** [comment]
Is `NETLIFY_AUTH_TOKEN` being used for that method?

**Comment by mikirobles** [comment]
![image](https://user-images.githubusercontent.com/25488110/61332876-c7123580-a7fb-11e9-9f1a-f109490de8fb.png)

**Comment by DavidWells** [comment]
Odd indeed.

The `netlify sites:list` command hits the same auth function: https://github.com/netlify/cli/blob/master/src/commands/sites/list.js#L11

Then checks for `process.env.NETLIFY_AUTH_TOKEN` here https://github.com/netlify/cli-utils/blob/master/src/index.js#L81

It shouldn't be hanging like that. 

How any sites does your account have? There might be a timeout happening with a large large list of sites because we are querying for all of them here https://github.com/netlify/cli/blob/master/src/commands/sites/list.js#L13

**Comment by mikirobles** [comment]
40 sites tops, and I just changed the credentials to an account with only 2 sites

**Comment by DavidWells** [comment]
`cli-utils` has not been updated and pushed. So the code that works isn't in the globally installed CLI...

(╯°□°)╯︵ ┻━┻

Stay tuned while we bump versions and re-release

**Comment by DavidWells** [comment]
Just released `netlify-cli/2.11.24`

Install that and give it a go. All commands should now respect `process.env.NETLIFY_AUTH_TOKEN`

**Comment by mikirobles** [comment]
It's working now after the updates, thanks!

**Comment by DavidWells** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉

Thanks for the report

Holler if you need anything else!

**Comment by sedghi** [comment]
Sorry for the bump, but I'm having an issue where the GitHub action is waiting for my confirmation for some reason although i'm giving my token

Here is the action link https://github.com/cornerstonejs/cornerstone3D/actions/runs/14499892052/job/40676802651

```
  - name: Deploy to Netlify
        run: |
          cd packages/docs
          netlify deploy --dir=build --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
```

results in 

![Image](https://github.com/user-attachments/assets/e9af8817-cf8d-4670-ae51-0e5ae074db83)
