### ISSUE TITLE
Support arbitrary dev commands alongside static server

### ISSUE THREAD

**Issue by ascorbic** [netlify/cli#3654]
**Is your feature request related to a problem? Please describe.**

Some frameworks don't use a dev server, but do have a command to watch source files and compile them to static files and/or functions. These watch commands can't be specified as the `dev` command because they don't open a port, and because specifying a command disables the static server.

**Describe the solution you'd like**

A way to specify a non-server `dev` command in toml and framework-info that would run as a long-running process alongside the static and functions servers. This could be a simple as making this the behaviour if no target port has been specified.

**Describe alternatives you've considered**

Telling users to run the `watch` command in a separate terminal to the `ntl dev` command. Using `npm-run-all` or equivalent.

**Additional context**
This is inspired by Remix, which needs this.

**Can you submit a pull request?**

Yes

> Pull requests are welcome! If you would like to help us add this feature, please check our
> [contributions guidelines](../../CONTRIBUTING.md).

**Comment by erezrokah** [comment]
cc @lukasholzer, we just talked about it yesterday in the context of https://github.com/netlify/cli/issues/410.

This is a valid use case we can support.

@ascorbic can you share a framework that needs this support?
Would we want to make this behavior default for this frameworks or only custom via the CLI.

If some frameworks needs this as a default, we would need to make the [`port` configuration in `framework-info` optional](https://github.com/netlify/framework-info/blob/963b9d8d860146db16a93f80ad9ea091fcce1e8f/src/frameworks/angular.json#L12) and have the CLI [not wait](https://github.com/netlify/cli/blob/d769ed2d485d4fe4f3041978c9e7eaa3264c4610/src/commands/dev/index.js#L104) on the port if it's not configured.

If it shouldn't be the default, we can make the change only in the CLI to allow specifying a command without a port.

**Comment by ascorbic** [comment]
@erezrokah The imemdiate example is Remix. They don't have public docs for this, but should do after they launch on Monday. They currently don't have a default buiild command, and generate this toml:

```toml
[build]
  functions = "netlify/functions"
  publish = "public"
  command = "npm run build"

[dev]
  functions = "netlify/functions"
  publish = "public"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

```

The instructions currently say this:

<details>
<summary>Remix on Netlify README</summary>

# Development

You will be running two processes during development when using Netlify as your server.

- Your Netlify server in one
- The Remix development server in another

```sh
# in one tab
$ npm run dev:netlify

# in another
$ npm run dev
```

Open up [http://localhost:3000](http://localhost:3000), and you should be ready to go!

If you'd rather run everything in a single tab, you can look at [concurrently](https://npm.im/concurrently) or similar tools to run both processes in one tab.
</details>
