### ISSUE TITLE
Presence of a [dev] block in Netlify TOML causes local dev to fail for functions

### ISSUE THREAD

**Issue by jlengstorf** [netlify/cli#3854]
**Describe the bug**

The presence of a `[dev]` block in `netlify.toml` causes functions to fail with what looks like a zisi error:
```
Request from ::1: GET /.netlify/functions/hello
TypeError: Cannot destructure property 'inputs' of '(intermediate value)' as it is undefined.
    at buildFunction (/Users/jlengstorf/.nvm/versions/node/v16.13.0/lib/node_modules/netlify-cli/src/lib/functions/runtimes/js/builders/zisi.js:39:11)
    at NetlifyFunction.build (/Users/jlengstorf/.nvm/versions/node/v16.13.0/lib/node_modules/netlify-cli/src/lib/functions/netlify-function.js:53:42)
    at FunctionsRegistry.buildFunctionAndWatchFiles (/Users/jlengstorf/.nvm/versions/node/v16.13.0/lib/node_modules/netlify-cli/src/lib/functions/registry.js:67:38)
```

**To Reproduce**

1. Create an empty folder
2. Add a "hello world" TypeScript function
    ```ts
    import { Handler } from "@netlify/functions";
    
    const handler: Handler = async (event, context) => {
      return {
        statusCode: 200,
        body: JSON.stringify({ message: "Hello World" }),
      };
    };
    
    export { handler };
    ```
3. Add a netlify.toml with a `[dev]` block
    ```toml
    [build]
      functions = "netlify/functions"
      publish = "public"
    
    [dev]
      functions = "netlify/functions"
      publish = "public"
    ```
4. Run `ntl dev`
5. Try to execute the function

Removing the `[dev]` block solves the issue

**Configuration**

```toml
[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  functions = "netlify/functions"
  publish = "public"
```

```bash
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 92.36 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmGlobalPackages:
    netlify-cli: 8.1.8
```

**Expected behavior**

**CLI Output**

If applicable, add the CLI output to help explain your problem.

**Additional context**
