### ISSUE TITLE
Splat not being passed as Query String

### ISSUE THREAD

**Issue by Hrishikesh-K** [netlify/cli#4273]
**Describe the bug:**

Using `splat` in sending query parameters to a destination doesn't seem to be working.

**To reproduce:**

Add the following to your `netlify.toml`:

```toml
[[redirects]]
  force = true
  from = "/foo/*"
  status = 301
  to = "/.netlify/functions/bar/?url=:splat"
```

Create a function with the following:

```js
exports.handler = async ({queryStringParameters}) => {
  return {
    body: JSOSN.strigify(queryStringParameters),
    statusCode: 200
  }
}
```

The output returns empty.

**Configuration**

```bash
  System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.44 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
  npmPackages:
    netlify-cli: ^9.4.0 => 9.4.0
```

**Expected behavior**

The query string should have some value if the requested URL was `/foo/bar/`.

**CLI Output**

N/A

**Additional context**

N/A
