### ISSUE TITLE
feat(command-dev): support base configuration

### ISSUE THREAD

**Issue by swyxio** [netlify/cli#433]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
we dont support `base`: https://www.netlify.com/docs/netlify-toml-reference/

report back to https://twitter.com/JTParrett/status/1126542833467498497 when done

**Comment by matuella** [comment]
Are there any alternatives for running a `netlify dev` that is inside a monorepo?

I.e:
```
netlify.toml
ui
- package.json
server
- package.json
```

**Comment by matuella** [comment]
My bad for not searching enough - we can achieve this by using the `--dir` or `-d` flag.
I.e.: Using the example above, I would simply run: `netlify dev -d ui`

**Comment by devuxer** [comment]
Just ran into this. It took a lot of tinkering, but I think I've got both Netlify Dev and CI deploys working.

My project directory looks something like this:

```
web-app/
├── .git/
├── back-end-stuff/
├── netlify-functions/
│     ├── build/
│     ├── src/
│     ├── package.json
│     └── tsconfig.json
├── web/
│     ├── src/
│     ├── gatsby-config.js
│     ├── package.json
│     └── tsconfig.json
├── netlify.toml
└── package.json
```

And here's my netlify.toml:

```toml
[build]
    base = "web"
    publish = "public"
    functions = "netlify-functions/build"

[dev]
    framework = "#custom"
    command = "npm run build-web"
    targetPort = 8000
```

And here's the `scripts` section of my **root** package.json:

```json
"scripts": {
    "netlify-dev": "netlify dev",
    "build-web": "cd web && npm run develop"
}
```

Hopefully this helps someone out, but it would be cleaner and a *lot* less confusing if this issue were addressed (i.e., "base" were supported for Netlify Dev, not just for builds).

**Comment by mjswensen** [comment]
Running into this, too. Unfortunately I wasn't able to get @devuxer 's magical incantation to work for my particular repository setup (though it was helpful during investigation, thank you!).

Current workaround is to temporarily move files around for dev, use a couple of commands to get everything up and running, and be careful what I commit and push. Then use preview deploys to validate manually before merging to master for production deploy.

Seems like the docs are mismatched somewhat with the UI as well—for example, the [file-based configuration docs](https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file) show the `functions` folder _including_ the base directory, but if you have to omit the base directory if you specify the functions folder in the UI, otherwise it gets added twice.

**Comment by devuxer** [comment]
@mjswensen , Sorry to mislead you. I was wrong. I believe my solution above only works in production. To use with netlify dev, I'm finding I need to have an extra copy of my built functions at web/netlify-functions/build. Note: I'm gitignoring that folder.

**Comment by mjswensen** [comment]
@devuxer No worries at all. I’ve been poking at this thing off and on for a few days and just can’t quite find a combination that works well for both dev and production. Looks like you’re in the same boat.

**Comment by devuxer** [comment]
@mjswensen, Another workaround appears to be just commenting out `base = "web"` from netlify.toml when testing in development. The downside of this is of course the risk of forgetting to uncomment it when pushing to production.

**Comment by RaeesBhatti** [comment]
@devuxer Can you please share your `netlify.toml` that works in production!

**Comment by devuxer** [comment]
Okay, I think I've gotten to a "good enough" solution for now. Still in the process of testing various aspects of this, but it at least appears that both my Gatsby site and functions are now building and showing up in both https://app.netlify.com/sites/[my-app]/functions as well as Netlify Dev.

Here's my current netlify.toml file:

```toml
[build]
    base = "web"
    publish = "public"
    functions = "netlify-functions"
    command = "npm install --global shx && npm install --prefix ../netlify-functions && npm run build --prefix ../netlify-functions && npm run build"

[dev]
    framework = "#custom"
    command = "npm run build --prefix netlify-functions && npm run develop --prefix web"
    targetPort = 8000
```

Here's what the production command does:

1. Installs shx globally (to allow for sh calls regardless of platform)
2. Installs node modules for /netlify-functions
3. Runs a build process that compiles all function files (which are written in TypeScript), then for each function, runs a little node script that...
    1. Assembles the resulting JavaScript plus a package.json and package-lock.json file into a folder
    2. Installs node modules for each folder
    3. Copies the folder to web/netlify-functions
4. Runs gatsby build for /web

The development command is a little simpler since it assumes shx and /netlify-functions dependencies have already been installed. Also, due to `base` not really working for dev, the `--prefix` flags are different.

I also tried to use netlify-lambda, but I frankly couldn't get it to work (I don't remember the errors I was getting, but I ultimately decided it would just be easier to roll my own solution).
