### ISSUE TITLE
v9.6.0 causes `out of memory` error when deploying

### ISSUE THREAD

**Issue by gavinhenderson** [netlify/cli#4359]
**Describe the bug**

Since upgrading to `v9.6.0` (from `9.5.0`) I consistently get a Javascript out of memory error when running `netlify deploy`.

I have tried upping the node memory limit incase I was just I was just slightly over the memory limit but I still get the error even after doubling the memory limit.

Nothing else has changed in my setup, if i drop the version it builds fine

**To Reproduce**

The best way to reproduce the error is run it within GitHub actions which runs the deploy. 

You can see the runs that consistently fail with the new version heere here: https://github.com/AceCentre/acecentre.org.uk/actions/workflows/deploy.yml?query=branch%3Aupdate-netlify

**Configuration**

My build command is:

```
yarn netlify deploy --alias=${{ needs.CalculateDeployKey.outputs.deploy-key }} --build --context deploy-preview --debug
```

<details>
 <summary>netlify.toml</summary>

```toml

 [[redirects]]
  from = "/trustees"
  to = "/about/trustees"
  status = 301

[[redirects]]
  from = "/account"
  to = "/my-acecentre"
  status = 301

[[redirects]]
  from = "/ace-centre-learning/my-courses"
  to = "/my-acecentre/courses"
  status = 301

[[redirects]]
  from = "/about/staff-member/*"
  to = "/about/staff/:splat"
  status = 301

[[redirects]]
  from = "/project/*"
  to = "/projects/:splat"
  status = 301

[[redirects]]
  from = "/news/*"
  to = "/blog/:splat"
  status = 301

[[redirects]]
  from = "/project/*"
  to = "/projects/:splat"
  status = 301

[[redirects]]
  from = "/news"
  to = "/blog"
  status = 301

[[redirects]]
  from = "/getting-started/faqs-frequently-asked-questions"
  to = "/getting-started"
  status = 301

[[redirects]]
  from = "/services/training"
  to = "/learning"
  status = 301

[[redirects]]
  from = "/services/information"
  to = "/services/advice-information"
  status = 301

[[redirects]]
  from = "/services/information/feedback/"
  to = "/form/information-appointment-feedback"
  status = 301

[[redirects]]
  from = "/privacy"
  to = "/page/privacy"
  status = 301

[[redirects]]
  from = "/ace-centre-privacy-policy-3"
  to = "/page/ace-centre-privacy-policy-3"
  status = 301

[[redirects]]
  from = "/purchase-terms-and-conditions"
  to = "/page/purchase-terms-and-conditions"
  status = 301

[[redirects]]
  from = "/safeguarding-policies"
  to = "/page/safeguarding-policies"
  status = 301

[[redirects]]
  from = "/wp-content/*"
  to = "https://backend.acecentre.org.uk/wp-content/:splat"
  status = 200

[[redirects]]
  from = "/ace-centre-learning"
  to = "/learning"
  status = 301

[[redirects]]
  from = "/resources/copyright-and-licence-terms-for-non-profit-items"
  to = "/page/copyright-and-licence-terms-for-non-profit-items"
  status = 301

[[redirects]]
  from = "/consent-form-2"
  to = "https://forms.office.com/Pages/ResponsePage.aspx?id=bFwgTJtTgU-Raj-O_eaPrEio9bWrHCRGoqxiKrWB3RlUMTJIR0NZVTNKMklEMjJHQ0dLQ1ZGMDBKTiQlQCN0PWcu"
  status = 301

[[redirects]]
  from = "/services/assessment"
  to = "/services/assessments"
  status = 301

[[redirects]]
  from = "/resources/electronic-text-based-comparison-chart"
  to = "https://backend.acecentre.org.uk/resources/electronic-text-based-comparison-chart"
  status = 301

[[redirects]]
  from = "/resources/electronic-text-based-features-checklist"
  to = "https://backend.acecentre.org.uk/resources/electronic-text-based-features-checklist"
  status = 301

[[redirects]]
  from = "/resources/developing-using-communication-book-templates"
  to = "/resources/developing-using-communication-book"
  status = 301

[[redirects]]
  from = "/services/assessment/nhs-referral"
  to = "/services/nhs/assessments"
  status = 301

[[redirects]]
  from = "/resources/access-to-low-tech-symbol-based-resources-when-pointing-is-difficult"
  to = "/resources/paper-based-resources-to-support-communication-for-adults-with-progressive-conditions"
  status = 301

[[redirects]]
  from = "/resources/using-low-tech-symbol-based-systems-with-children"
  to = "/resources/access-to-paper-based-symbol-resources-when-pointing-is-difficult"
  status = 301

[[redirects]]
  from = "/resources/getting-started-aac"
  to = "/resources/all?category=made-by-ace&subcategory=e-books"
  status = 301

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "/netlify-plugins/sitemap"

[[plugins]]
  package = "/netlify-plugins/expose-env-variables"

[[plugins]]
  package = "/netlify-plugins/output-config"

[[plugins]]
  package = "/netlify-plugins/copy-redirects"

[build]
  command = "yarn build && yarn build-function"
  publish = ".next"</details>

```

</details>

<details>
 <summary>package.json</summary>

```json

 {
  "name": "acecentre.org.uk",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "test": "jest --forceExit",
    "dev": "ENV=development next dev",
    "dev:cache": "USE_DATA_FETCHING_CACHE=true ENV=development next dev",
    "dev:live": "USE_LIVE_DATA=true ENV=development next dev",
    "build": "yarn build:next",
    "build:next": "next build",
    "start": "next start",
    "storybook": "start-storybook -p 6006 -s ./public",
    "build-storybook": "rm -rf out/design-system && mkdir -p out/design-system && build-storybook -o out/design-system --quiet -s ./public",
    "cypress:open": "cypress open",
    "cypress:run": "cypress run",
    "cypress:integration:open": "CYPRESS_BASE_URL=https://integration--acecentreorguk.netlify.app cypress open --config retries=0",
    "lighthouse": "lhci autorun",
    "plop": "plop",
    "build-sitemap": "next-sitemap",
    "build-function": "esbuild .netlify/functions-internal/add-to-cohort.js --bundle --platform=node --outfile=./.netlify/functions-internal/add-to-cohort-background.js"
  },
  "dependencies": {
    "@chakra-ui/react": "1.8.5",
    "@emotion/react": "11.8.1",
    "@emotion/styled": "11.8.1",
    "@lukeed/uuid": "2.0.0",
    "@mailchimp/mailchimp_marketing": "3.0.74",
    "@material-ui/core": "4.12.3",
    "@material-ui/icons": "4.11.2",
    "@netlify/functions": "1.0.0",
    "@octokit/rest": "18.12.0",
    "@react-aria/focus": "3.5.2",
    "@react-aria/interactions": "3.8.1",
    "@react-aria/radio": "3.1.8",
    "@react-aria/visually-hidden": "3.2.5",
    "@react-stately/radio": "3.3.4",
    "@slack/bolt": "3.9.0",
    "@stripe/react-stripe-js": "1.7.0",
    "@stripe/stripe-js": "1.23.0",
    "async-redis": "2.0.0",
    "esbuild": "0.14.23",
    "etag": "1.8.1",
    "framer-motion": "6.2.7",
    "fuse.js": "6.5.3",
    "graphql": "16.3.0",
    "graphql-playground-middleware-express": "1.7.23",
    "graphql-request": "4.0.0",
    "image-type": "4.1.0",
    "is-svg": "4.3.2",
    "jwt-decode": "3.1.2",
    "linkedom": "0.14.2",
    "lodash": "4.17.21",
    "next": "12.1.0",
    "next-iron-session": "4.2.0",
    "next-transpile-modules": "9.0.0",
    "node-fetch": "3.2.0",
    "nprogress": "0.2.0",
    "polyfill-object.fromentries": "1.0.1",
    "posthog-js": "1.17.8",
    "prom-client": "13.2.0",
    "react": "17.0.2",
    "react-accessible-accordion": "4.0.0",
    "react-dom": "17.0.2",
    "react-lite-youtube-embed": "2.2.1",
    "sharp": "0.30.1",
    "treeify-js": "1.0.8",
    "turndown": "7.1.1"
  },
  "devDependencies": {
    "@lhci/cli": "0.9.0",
    "@netlify/plugin-nextjs": "4.2.7",
    "@storybook/addon-actions": "6.4.19",
    "@storybook/addon-essentials": "6.4.19",
    "@storybook/addon-links": "6.4.19",
    "@storybook/react": "6.4.19",
    "@swc/core": "1.2.143",
    "@swc/jest": "0.2.17",
    "@swc/register": "0.1.10",
    "@testing-library/cypress": "8.0.2",
    "cypress": "9.5.0",
    "cypress-tags": "0.3.0",
    "eslint": "8.9.0",
    "eslint-config-next": "12.1.0",
    "eslint-plugin-cypress": "2.12.1",
    "eslint-plugin-jest": "26.1.1",
    "eslint-plugin-react": "7.28.0",
    "fast-xml-parser": "4.0.3",
    "got": "11.8.3",
    "jest": "27.5.1",
    "jest-css-modules-transform": "4.3.0",
    "mock-fs": "5.1.2",
    "mysql2": "2.3.3",
    "netlify-cli": "9.6.0",
    "next-sitemap": "2.4.6",
    "nock": "13.2.4",
    "plop": "3.0.5",
    "storybook-css-modules-preset": "1.0.8"
  }
}
```

</details>

<details>
<summary>envinfo</summary>

```
System:
    OS: Linux 5.11 Ubuntu [20](https://github.com/AceCentre/acecentre.org.uk/runs/5301137974?check_suite_focus=true#step:7:20).04.3 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 2.63 GB / 6.78 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.19.0 - /opt/hostedtoolcache/node/14.19.0/x64/bin/node
    Yarn: 1.[22](https://github.com/AceCentre/acecentre.org.uk/runs/5301137974?check_suite_focus=true#step:7:22).17 - /usr/local/bin/yarn
    npm: 6.14.16 - /opt/hostedtoolcache/node/14.19.0/x64/bin/npm
  npmPackages:
    netlify-cli: 9.6.0 => 9.6.0
```

</details>

**Expected behavior**

The deploy to happen without an out of memory error

**CLI Output**

[See full log here (its a long log so you might have to wait a second for it to jump to the right line)](https://github.com/AceCentre/acecentre.org.uk/runs/5300873089?check_suite_focus=true#step:7:48461)

<details>
<summary>CLI Output</summary>

```
Configuration path: /home/runner/work/acecentre.org.uk/acecentre.org.uk/netlify.toml
Deploying to draft URL...
​
❯ Initial build environment
context: deploy-preview
cwd: /home/runner/work/acecentre.org.uk/acecentre.org.uk
featureFlags: []
mode: cli
siteId: ***
- Hashing files...
- Looking for a functions cache...
✔ Deploying functions from cache (use --skip-functions-cache to override)
​
❯ UI build settings
baseRelDir: true
build:
  command: echo "NETLIFY=$NETLIFY" >> .env && echo "CONTEXT=$CONTEXT" >> .env && yarn build
  publish: out/
plugins:
  - inputs: {}
    package: '@netlify/plugin-nextjs'

<--- Last few GCs --->

[1664:0x5384e50]   540579 ms: Scavenge 543.1 (564.7) -> 528.4 (565.9) MB, 9.9 / 0.0 ms  (average mu = 0.981, current mu = 0.981) allocation failure 
[1664:0x5384e50]   552407 ms: Scavenge 548.9 (570.4) -> 534.1 (571.9) MB, 9.2 / 0.0 ms  (average mu = 0.981, current mu = 0.981) allocation failure 
[1664:0x5384e50]   562505 ms: Scavenge 554.5 (575.9) -> 539.6 (577.4) MB, 11.4 / 0.0 ms  (average mu = 0.981, current mu = 0.981) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 0xa3aaf0 node::Abort() [/opt/hostedtoolcache/node/14.19.0/x64/bin/node]
 2: 0x970199 node::FatalError(char const*, char const*) [/opt/hostedtoolcache/node/14.19.0/x64/bin/node]
 3: 0xbba45e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/opt/hostedtoolcache/node/14.19.0/x64/bin/node]
 4: 0xbba7d7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/opt/hostedtoolcache/node/14.19.0/x64/bin/node]
 5: 0xd769e5  [/opt/hostedtoolcache/node/14.19.0/x64/bin/node]
 6: 0xd4f215  [/opt/hostedtoolcache/node/14.19.0/x64/bin/node]
 7: 0xed874e  [/opt/hostedtoolcache/node/14.19.0/x64/bin/node]
 8: 0xede004  [/opt/hostedtoolcache/node/14.19.0/x64/bin/node]
 9: 0xede2c8  [/opt/hostedtoolcache/node/14.19.0/x64/bin/node]
10: 0xf314fb v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes) [/opt/hostedtoolcache/node/14.19.0/x64/bin/node]
11: 0xf86212 v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::Maybe<v8::internal::ShouldThrow>, v8::internal::StoreOrigin) [/opt/hostedtoolcache/node/14.19.0/x64/bin/node]
12: 0xf8950f v8::internal::Object::SetProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>) [/opt/hostedtoolcache/node/14.19.0/x64/bin/node]
13: 0x10b53b5 v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>) [/opt/hostedtoolcache/node/14.19.0/x64/bin/node]
14: 0x10b6457 v8::internal::Runtime_SetKeyedProperty(int, unsigned long*, v8::internal::Isolate*) [/opt/hostedtoolcache/node/14.19.0/x64/bin/node]
15: 0x1448e19  [/opt/hostedtoolcache/node/14.19.0/x64/bin/node]
Aborted (core dumped)
error Command failed with exit code 134.
info Visit [yarnpkg.com/en/docs/cli/run](https://yarnpkg.com/en/docs/cli/run) for documentation about this command.
Error: Process completed with exit code 134.
```

</details>
