### ISSUE TITLE
GitHub CI action to deploy site failed - reason: `getaddrinfo ENOTFOUND api.netlify.com`

### ISSUE THREAD

**Issue by liyasthomas** [netlify/cli#4533]
### Describe the bug

I've the following step in a GitHub action workflow:
```	
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          args: deploy --prod

```

The above step failed with this error:

```
Error: request to https://api.netlify.com/api/v1/sites/*** failed, reason: getaddrinfo ENOTFOUND api.netlify.com

```

### Steps to reproduce

[Link to GitHub action run ->](https://github.com/hoppscotch/hoppscotch/runs/6036186685?check_suite_focus=true)

### Configuration

https://github.com/hoppscotch/hoppscotch/blob/main/netlify.toml

### Environment

```
  System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 85.30 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - ~/.nvm/versions/node/v15.11.0/bin/node
    npm: 7.20.3 - ~/.nvm/versions/node/v15.11.0/bin/npm
  npmGlobalPackages:
    netlify-cli: 9.16.6

```
