### ISSUE TITLE
Netlify Dev Server Not Starting

### ISSUE THREAD

**Issue by hashmaster3k** [netlify/cli#4686]
### Describe the bug

I was trying to determine why my functions were being loaded but not found. I opened a [support thread ](https://answers.netlify.com/t/loaded-function-not-found-in-developement/66936/5)on the Netlify forms, which lead me to here. Apparently my development server is not starting and I cannot reach localhost:8888

Here is a screenshot of my terminal once running the ```netlify dev``` command

<img width="1437" alt="Screen Shot 2022-06-09 at 5 07 24 PM" src="https://user-images.githubusercontent.com/40395852/172959659-ad8a76b1-a3e2-44dd-a055-6ed4fb1800eb.png">

The following box does not show up
```
   ┌──────────────────────────────────────────────────────────────┐
   │                                                              │
   │   [Netlify Dev] Server now ready on http://localhost:8888    │
   │                                                              │
   └──────────────────────────────────────────────────────────────┘
```

### Steps to reproduce

Repository is private thus unable to share exact repo.

### Configuration

```toml
[context.production]
  command = "make production"
[context.staging]
  command = "make staging"
[functions]
  node_bundler = "esbuild"
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = false
```

### Environment

  **System:**
- OS: macOS 12.3.1
- CPU: (8) arm64 Apple M1
- Memory: 81.06 MB / 8.00 GB
- Shell: 5.8 - /bin/zsh

**Binaries:**
- Node: 18.3.0 - /opt/homebrew/bin/node
- Yarn: 1.22.17 - /opt/homebrew/bin/yarn
- npm: 8.11.0 - /opt/homebrew/bin/npm

**npmGlobalPackages:**
- netlify-cli: 10.5.0
