### ISSUE TITLE
"atob is not defined" while using dev command with graph param

### ISSUE THREAD

**Issue by Igloczek** [netlify/cli#4868]
### Describe the bug

When running `netlify dev --graph` the process failing with error `atob is not defined`.

I've managed to pin down the source of this bug, it's `netlify-onegraph-internal` package, line 110 of `dist/oneGraphClient.js` inside of `getGraphJwtForSite` function.

```js
var payload = JSON.parse(atob(base64Payload));
```

while should be:

```js
var payload = JSON.parse(Buffer.from(base64Payload, 'base64').toString());
```

Unfortunately, there are more problems with accessing the `window` object in this file, for example few lines below is `performance.now()`. So kinda looks like browser code is running on the server side, while it shouldn't.

After changing all `performance.now()` to `Date.now()` (while I'm aware it's not the same thing), it works fine on the server side.

### Steps to reproduce

1. Clone this template https://github.com/netlify-templates/astro-quickstart
2. Run `npm install`
3. Run `netlify dev --graph --sessionId={yourId}`

### Configuration

```toml
# example netlify.toml
[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

[[plugins]] 
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true
  
  [plugin.inputs]
    enable = false
```

### Environment

MacOS Monterey 12.5
Volta + Node.js 14.19.3 + npm 7.12.0
