### ISSUE TITLE
Redirect from root fails in dev, works on deploy

### ISSUE THREAD

**Issue by fineline** [netlify/cli#517]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

The following config works when deployed to netlify, but fails in netlify dev:

```toml
[[redirects]]
  from = "/"
  to = "/home"
  status = 200
```

I have tested other redirects such as:

```toml
[[redirects]]
  from = "/test"
  to = "/home"
  status = 200
```

and that works fine, so it appears to be just the root URL redirect (rewrite).

**- If the current behavior is a bug, please provide the steps to reproduce.**

* Add code above to netlify.toml
* Ensure a file exists in `/static/home/index.html`
* run `netlify dev`
* browse to http://localhost:8888
* Observe the message "Forbidden"

**- What is the expected behavior?**

When deployed to netlify, the page at `/home/index.html` is displayed for the raw domain URL. I would expect this same behaviour in netlify dev.

**- Local Environment Information**

────────────────────┐
 Netlify Site Info  │
────────────────────┘
 ›   Warning: Did you run `netlify link` yet?
 ›   Error: You don't appear to be in a folder that is linked to a site
