### ISSUE TITLE
Version 16.x broke the build path resolution

### ISSUE THREAD

**Issue by CamiloTerevinto** [netlify/cli#5949]
### Describe the bug

I have a GitHub action that does `cd ./out && netlify deploy --dir . --site *** --prod --auth ***`.

Last week, using 15.x, this gave me a log of:

> Deploy path: /home/runner/work/www/www/out

Now, it's giving a log of:

> Deploy path: /home/runner/work/www/www

Which, of course, broke my site, as the expected files are in a sub-folder.

### Steps to reproduce

Run `netlify deploy` passing the current directory (`.`)

### Configuration

N/A

### Environment

```
System:
    OS: Linux 5.[15](https://github.com/CamiloTerevinto/www/actions/runs/5860077734/job/15887416498#step:9:16) Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
    Memory: 5.48 GB / 6.77 GB
    Container: Yes
    Shell: 5.1.[16](https://github.com/CamiloTerevinto/www/actions/runs/5860077734/job/15887416498#step:9:17) - /bin/bash
  Binaries:
    Node: 18.[17](https://github.com/CamiloTerevinto/www/actions/runs/5860077734/job/15887416498#step:9:18).0 - /usr/local/bin/node
    Yarn: 1.22.[19](https://github.com/CamiloTerevinto/www/actions/runs/5860077734/job/15887416498#step:9:20) - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 16.0.3
```

**Comment by CamiloTerevinto** [comment]
Note that a simple workaround is to add again the relative path:

`netlify deploy --dir ./out --site *** --prod --auth ***`

But this is likely going to annoy people.

**Comment by lukasholzer** [comment]
Hey @CamiloTerevinto, first of all, sorry that we've broken your workflow, and thank you for raising this issue!

Can you share more details about your repository, or if easily possible, share some reproducible example that helps us fix the issue?

1. Is it a mono repository (like pnpm workspaces, lerna, etc)
2. can you describe the folder structure and where you execute the command in the CI (process working directory – e.g. repository root)?
3. like cwd, etc...
4. how does your configuration file look like? do you use a `netlify.toml`?

**Comment by jlengstorf** [comment]
I ran into this issue as well in an Nx monorepo: https://github.com/learnwithjason/learnwithjason.dev

As of 16.x the Netlify CLI is trying to use the wrong directories to run e.g. `ntl dev`. Revert to 15.11.0 fixes the problem and the site operates normally.

**Comment by CamiloTerevinto** [comment]
Hey @lukasholzer, sorry I missed the notification for your comment. 

1. It's a .NET repo where the static files are generated and stored at the `./out` folder (index.html, other HTML files at the root folder, and then assets and other folders). Nothing NodeJs/npm/etc related.
2. Everything for Netlify is stored inside the `./out` folder. The commands run from inside this folder (see code below)
3. I don't use a config file, I just push the files directly.

```yaml
- name: Run the ssg tool
  run: ssg --output ${GITHUB_WORKSPACE}/out [other irrelevant params]

- name: Use Node.js 16.x
  uses: actions/setup-node@v3

- name: Install the Netlify CLI
  run: npm install netlify-cli -g

- name: Push to Netlify
  run: netlify deploy --dir ./out --site [obfuscated] --prod --auth ${{secrets.NETLIFY_TOKEN}}
```

The last step, which worked with the latest 15.x, used to be `cd ./out && netlify deploy --dir . --site [obfuscated] --prod --auth ${{secrets.NETLIFY_TOKEN}}`
