### ISSUE TITLE
[BUG] CLI (and API) is broken when used with "Personal access tokens"

### ISSUE THREAD

**Issue by fprochazka** [netlify/cli#622]
## Short reproduce

I'm unable to use netlify-cli (or API for that matter) with "Personal access token" - all commands end with error.

1. install netlify-cli `npm install netlify-cli -g`
2. create personal access token https://app.netlify.com/user/applications#personal-access-tokens
3. run `NETLIFY_AUTH_TOKEN=secret-token netlify sites:list`

environment:

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.13.1 - /usr/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.12.1 - /usr/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 70.0.1
```

status:

```
$ NETLIFY_AUTH_TOKEN=secret-token netlify status --verbose 
──────────────────────┐
 Current Netlify User │
──────────────────────┘
FetchError: invalid json response body at https://api.netlify.com/api/v1/accounts reason: Unexpected end of JSON input
    at ~/.config/yarn/global/node_modules/node-fetch/lib/index.js:272:32
    at async NetlifyAPI.listAccountsForUser (~/.config/yarn/global/node_modules/netlify/src/open-api/index.js:160:20)
    at async StatusCommand.run (~/.config/yarn/global/node_modules/netlify-cli/src/commands/status/index.js:29:22)
    at async StatusCommand._run (~/.config/yarn/global/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (~/.config/yarn/global/node_modules/@oclif/config/lib/config.js:151:9)
    at async Main.run (~/.config/yarn/global/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (~/.config/yarn/global/node_modules/@oclif/command/lib/command.js:44:20)
```

api:

```
curl -v -H 'User-Agent: Test (filip@prochazka.su)' 'https://api.netlify.com/api/v1/sites?access_token=secret-token'
```

```
curl -v -H 'User-Agent: Test (filip@prochazka.su)' -H "Authorization: Bearer secret-token" 'https://api.netlify.com/api/v1/sites'
```

all my attempts end with 

```
HTTP/1.1 401 Unauthorized
```

which I had to find out using direct API calls and the netlify-cli did not tell me that, instead, all got was a cryptic "Unexpected end of JSON input"

When I run `netlify login` and use the oauth workflow of opening browser and confirming the login, all the netlify-cli commands work as expected. Which is obviously not what I would want to do in CI.

## Full reproduce

I'm trying to integrate netlify-cli into our Gitlab-CI build (gitlab and runners are on-premises). 

I've created a custom docker image `node-js/netlify-cli:2-alpine`, built like this:

```Dockerfile
FROM node:12.13-alpine

RUN set -ex \
 && apk add --no-cache curl git \
 && npm install netlify-cli@2.21.0 -g
```

This image is then used to run netlify tasks.

```yml
stages:
  - build
  - deploy

variables:
  JEKYLL_VERSION: '3.8'

job-build:
  stage: build
  tags: ['docker', 'small']
  image: jekyll/jekyll:$JEKYLL_VERSION
  variables:
    JEKYLL_DATA_DIR: $CI_PROJECT_DIR
  before_script:
    - bundle install
  script:
    - jekyll build -d dist
  artifacts:
    paths:
      - dist/*

job-deploy-prod:
  stage: deploy
  tags: ['docker', 'small']
  image: node-js/netlify-cli:2-alpine
  script:
    - DEBUG=* netlify deploy --site $NETLIFY_SITE_ID --message "$(git show -s --format=%s)" --prod
  dependencies:
    - job-build
  only:
    - master
```

the job is configured with `NETLIFY_SITE_ID` and `NETLIFY_AUTH_TOKEN` ENV variables

![image](https://user-images.githubusercontent.com/158625/69746178-00609780-1144-11ea-828b-c194f54d7f1f.png)
