### ISSUE TITLE
netlify functions:create no longer provides a list of templates to choose from for serverless functions

### ISSUE THREAD

**Issue by nickytonline** [netlify/cli#6250]
### Describe the bug

Running `netlify functions:create` no longer provides a list of templates to choose from for serverless functions.

Note that the templates still work for edge functions.

### Steps to reproduce

1. Ensure you're on this version of the CLI, `netlify-cli/17.9.0 darwin-arm64 node-v20.9.0`
2. The assumption is you've run `ntl init` already and your repo is configured with Netlify.
3. Run `ntl functions:create`
4. You're prompted to select the type of function. Select Serverless function (Node/Go)

	```
	? Select the type of function you'd like to create 
	  Edge function (Deno) 
	❯ Serverless function (Node/Go) 
	```
5. At the next step select JavaScript. ES module warnings appear and there are no templates to select from.

	```
	? Select the language of your function JavaScript
	(node:66419) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
	(Use `node --trace-warnings ...` to show where the warning was created)
	(node:66419) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
	(node:66419) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
	(node:66419) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
	? Pick a template (Use arrow keys or type to search)
	❯ [hello-world] Basic function that shows async/await usage, and 
	response formatting 
	  [identity-signup] Identity Signup: Triggered when a new Netlify
	 Identity user confirms. Assigns roles and extra metadata 
	  ──────────────
	  Clone template from GitHub URL 
	  Report issue with, or suggest a new template 
	(Move up and down to reveal more choices)
	```
7. If you select TypeScript instead, similar warnings appear.

	```
	? Select the language of your function TypeScript
	(node:66715) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
	(Use `node --trace-warnings ...` to show where the warning was created)
	(node:66715) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
	? Pick a template (Use arrow keys or type to search)
	  ──────────────
	❯ Clone template from GitHub URL 
	  Report issue with, or suggest a new template
	```
	
![CleanShot 2023-12-05 at 17 46 12](https://github.com/netlify/cli/assets/833231/879e0b85-6559-44b9-b519-889c20b60cb4)

### Configuration

I'm aware there is no build command. We currently handle the build command in the UI as we are not configured as a true monorepo yet.

```toml
[build.environment]
NODE_VERSION = "18"

[context.alpha]
environment = { CHANNEL = "alpha" }

[context.beta]
environment = { CHANNEL = "beta" }

[dev]
command = "next dev -p 3001"
port = 3000
targetPort = 3001

[functions.render]
# see https://github.com/alixaxel/chrome-aws-lambda/issues/270#issuecomment-1098349498
external_node_modules = ["chrome-aws-lambda"]

[functions]
deno_import_map = "./netlify/edge-functions/deno.json"

[[redirects]]
from = "https://insight.opensauced.pizza/*"
to = "https://insights.opensauced.pizza/:splat"
status = 301
force = true

[[redirects]]
from = "https://insights.opensauced.pizza/*"
to = "https://app.opensauced.pizza/:splat"
status = 301
force = true

[[redirects]]
from = "https://beta.insights.opensauced.pizza/*"
to = "https://beta.app.opensauced.pizza/:splat"
status = 301
force = true
```

### Environment

  System:
    OS: macOS 14.1.2
    CPU: (12) arm64 Apple M2 Max
    Memory: 567.70 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.10.2 - ~/.nvm/versions/node/v20.9.0/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  npmGlobalPackages:
    netlify-cli: 17.9.0
