### ISSUE TITLE
[dev redirects] ignore redirects in netlify toml for dev  server only

### ISSUE THREAD

**Issue by waynevanson** [netlify/cli#640]
**- Do you want to request a _feature_ or report a _bug_?**
Feature if not apparent already.

I want the attached redirect to be ignored only on the dev server/ only implemented on the build server.

I'm redirecting because I'm using an internal router for a react app.
```toml
[[redirects]]
from = '/*'
to = '/'
status = 200

[build]
publish = 'build'
functions = 'functions'
command = 'yarn build:static'

[dev]
command = 'yarn start:parcel'
publish = '.server'
functions = 'src/lambda'
```

**- What is the current behavior?**
Netlify dev server at `:8080` doesn't work because of the redirect.

Running the original port `:1234`in parcel works as per normal. I want to use the dev server because it holds my lambda functions.

**- What is the expected behavior?**
Should work flawlessly.

**- Local Environment Information**
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 13.1.0 - ~/.nvm/versions/node/v13.1.0/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.13.0 - ~/.nvm/versions/node/v13.1.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.70

────────────────────┐
 Netlify Site Info  │
────────────────────┘
Current site: pfm-dev
Netlify TOML: /home/wayne/Documents/pfm-react/netlify.toml
Admin URL:    https://app.netlify.com/sites/pfm-dev
Site URL:     https://pfm-dev.waynevanson.com
Site Id:      c8e86cac-2122-4399-bc37-986024112a61
