### ISSUE TITLE
Nuxt 3, dist folder not created with github actions.

### ISSUE THREAD

**Issue by pochat** [netlify/cli#6534]
### Describe the bug

Hi all,

I hope are well.

Nuxt 3 does not create the dist folder when using GitHub actions. I followed the boilerplate in this link. https://github.com/marketplace/actions/netlify-actions Still, the dist folder is not created after numerous attempts.

Sitename: https://csci-e-114-final-project-pochat.netlify.app/
Repo: https://github.com/cscie114/csci-e-114-final-project-pochat

![image](https://github.com/netlify/cli/assets/48400262/63d1356f-1084-40a0-9490-baebaf9d380c)

Error:
```
Deploy path: /home/runner/work/csci-e-114-final-project-pochat/csci-e-114-final-project-pochat/dist
 ›   Error: The deploy directory "/home/runner/work/csci-e-114-final-project-pochat/csci-e-114-final-project-pochat/dist" has not been found. Did you forget to run 'netlify build'?
Error: Process completed with exit code 1.
```

My yml file:
```
name: Deploy to Netlify

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 18.0.0

      - name: Clean 
        run: npm ci 

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt app
        run: npm run build

      - name: Linked Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

        run: netlify deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod

```

Any help is appreciated.

### Steps to reproduce

1. Open my repo: https://github.com/cscie114/csci-e-114-final-project-pochat
2. Do a commit to trigger the yml file with github actions
3. Read the results on the github actions website

### Environment

  System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 58.94 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.0.0 - ~/.nvm/versions/node/v22.0.0/bin/node
    npm: 10.6.0 - ~/.nvm/versions/node/v22.0.0/bin/npm
