### ISSUE TITLE
CLI authorization issue on GitHub Actions

### ISSUE THREAD

**Issue by bugnificent** [netlify/cli#7245]
### Describe the bug

CLI authorization issue on GitHub Actions

### Steps to reproduce

Having issues on Deploy part from GitHub Actions, CLI command works fine on my terminal/local but not pushing to the prod(workflow doesnt give any error, completing), and after trying numerous of possibilities like passing site and auth from argument, not using @cli/master none of them able to push to the production.

![Image](https://github.com/user-attachments/assets/f07c9ece-355c-4240-b0a1-466cede0de7a)

### Configuration

```yml
name: Assertions and static report

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer netlify-cli

      - name: Unlighthouse assertions and client
        run: unlighthouse-ci --site yusufasik.com --debug --build-static --throttle --no-cache --samples 3

      - name: Deploy
        uses: netlify/actions/cli@master
        with:
         args: deploy --dir=.unlighthouse --prod --message="New Release Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
```

### Environment

  System:
    OS: Windows 11 10.0.26100
    CPU: (12) x64 AMD Ryzen 5 7600 6-Core Processor
    Memory: 20.82 GB / 31.22 GB
  Binaries:
    Node: 22.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 11.3.0 - C:\Program Files\nodejs\npm.CMD
