### ISSUE TITLE
`netlify-cli`: ReferenceError: Response is not defined

### ISSUE THREAD

**Issue by daisypunk** [netlify/cli#7287]
### Describe the bug

No code changes have happened on my end. A recurring smoketest deployment surfaced this issue starting approximately four days ago (5/7).

When deploying to Netlify via `netlify deploy` from a github `deployment.yml` workflow, the deployment fails silently with `ReferenceError: Response is not defined`.

See: https://answers.netlify.com/t/netlify-cli-referenceerror-response-is-not-defined/147257

### Steps to reproduce

Deploy any site (or functions) by pushing a commit to a repo which has the following `deployment.yml`:

```
     - name: Deploy using Netlify CLI
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          args: deploy --dir=dist/site --functions=dist/functions --prod
```

### Environment

No thank you (this would leak PII - I'd suggest scoping this down to version info instead)
