### ISSUE TITLE
Deployed filenames cannot contain # or ? characters

### ISSUE THREAD

**Issue by Th3S4mur41** [netlify/cli#7340]
### Describe the bug

After updating netlify-cli from v21 to v22, deployment fails with the following error:

```sh
Internal error during "options.onPostBuild"                   
────────────────────────────────────────────────────────────────
​
  Error message
  Error: Invalid filename plugins/node_modules/es6-iterator/test/#/chain.js. Deployed filenames cannot contain # or ? characters
```

### Steps to reproduce

Create a javascript function that with the following imports:

```js
import { graphql } from '@octokit/graphql';
import { createAppAuth } from '@octokit/auth-app';
import * as updateMetadata from 'dependabot-pull-request-action/src/dependabot/update_metadata.ts';
```

Bundle the script with the following command:
```sh
esbuild src/github_event_handler.mjs --bundle --outfile=dist/github_event_handler.js --platform=neutral --format=esm --target=es2020 --external:node:* --minify
```

Build netlify functions and edge function that imports the javascript function

Deploy to netlify with netlify-cli 22.1.2

### Configuration

[build]
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[[redirects]]
  from = "/webhooks/merge-pr"
  to = "/.netlify/edge-functions/merge-pr"
  status = 200

### Environment

  System:
    OS: Linux 6.8 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 3.52 GB / 7.75 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.19.0 - /usr/local/share/nvm/versions/node/v20.19.0/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.2 - /usr/local/share/nvm/versions/node/v20.19.0/bin/npm
    pnpm: 10.6.4 - /usr/local/share/nvm/versions/node/v20.19.0/bin/pnpm
  npmPackages:
    netlify-cli: ^22.1.2 => 22.1.2

**Comment by Th3S4mur41** [comment]
The `node_modules` folder is being created in the .netlify output by `netlify build` command, when building the edge-function.

Attempts to skip plugins installation like updating the `netlify.toml` as follow: have proven unsuccessful

```toml
[build]
  edge_functions = "netlify/edge-functions"
  publish = "."

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"
  # Disable automatic plugin installation
  NETLIFY_EXPERIMENTAL_BUILD_NODE_PATH = "false"
  NETLIFY_DISABLE_PLUGINS = "true"

[[redirects]]
  from = "/webhooks/merge-dependabot-pr"
  to = "/.netlify/edge-functions/merge-dependabot-pr"
  status = 200		 
```

So this seems related to https://github.com/netlify/build/issues/2193
But in this case the deployed folder is not the root folder, but explicitely the `.netlify` folder that is created by the `netlify build` command and the node_modules folder in question is added by the same command to the plugins folder inside .netlify.

It's worth noting the the generated netlify.toml in this case also does not have any plugins installed as `plugins = []` would suggest
