### ISSUE TITLE
Function redirects works for netlify dev but not production

### ISSUE THREAD

**Issue by bodaso** [netlify/cli#870]
**- What is the current behavior?**

In my Gatsby app, I have these rules for redirects in my `netlify.toml`

```toml
[build]
    publish = "public"
    command = "npm run build"
    functions = "functions"

[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"

[[redirects]]
    from = "/api/*"
    to = ".netlify/functions/:splat"
    status = 200
```

My app works fine when I do `netlify dev`, all functions redirect to /api like so 

```
Request URL: http://localhost:8888/api/get-items
Request Method: GET
Status Code: 200 OK
```

but when I deploy to prod, functions fetch result in 404 error

```
Request URL: https://xxx.netlify.app/api/get-items
Request Method: GET
Status Code: 404 
```

Although they still work on `https://xxx.netlify.app/.netlify/functions/get-items`

How can I keep the redirect behaviours consistent on `netlify dev` and prod?

────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 75.0
    Safari: 13.1
  npmGlobalPackages:
    netlify-cli: 2.48.0

netlify-cli/2.48.0 darwin-x64 node-v12.16.3
