### ISSUE TITLE
Netlify Dev exits right after outputting "Connected! Waiting for localhost:34567"

### ISSUE THREAD

**Issue by fregante** [netlify/cli#901]
**- Do you want to request a _feature_ or report a _bug_?**

_bug_

**- What is the current behavior?**

`netlify dev` exits after `Connected! Waiting for localhost:34567`
```sh
❯ netlify dev

◈ Netlify Dev ◈
◈ Starting Netlify Dev with #custom
Waiting for localhost:3000.
◈ Functions server is listening on 34567

1

Connected!
Waiting for localhost:34567.⏎ 
```

This instantly exits with 0 and `localhost:34567` isn't available. 

**- If the current behavior is a bug, please provide the steps to reproduce.**

```toml
[build]
  publish = "dist"
  command = "npm run build"
  functions = ".netlify/functions/"
[dev]
  command = "echo 1"
  framework = "#custom"
  targetPort = 3000
```

Note: the server on localhost:3000 is running separately and it works.

```sh
netlify dev
```

**- What is the expected behavior?**

I think it shouldn't exit and `localhost:34567` should be accessible

**- Local Environment Information**

```
❯ netlify version --verbose
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 7.30GHz
  Binaries:
    Node: 12.15.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 2.50.0

netlify-cli/2.50.0 darwin-x64 node-v12.15.0
```
