### ISSUE TITLE
`netlify dev` proxy doesn't forward search parameters

### ISSUE THREAD

**Issue by kidonng** [netlify/cli#921]
**- Do you want to request a _feature_ or report a _bug_?**

Bug

**- What is the current behavior?**

`netlify dev` proxy won't forward search parameters in URL, thus returning the same content for actually different resources.

![image](https://user-images.githubusercontent.com/44045911/82726503-3cea0600-9d17-11ea-9d47-f6714194f255.png)
![image](https://user-images.githubusercontent.com/44045911/82726523-52f7c680-9d17-11ea-99e6-b5446b60a5f5.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**

In `netlify.toml`:

```toml
[[redirects]]
from = "/api/*"
to = "https://api.readhub.cn/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
```

Visit `localhost:port/api/topic` and `localhost:port/api/topic?lastCursor=253822`, and both return the same content.

**- What is the expected behavior?**

`netlify dev` proxies the URL correctly (the two address should return the corresponding results).

**- Local Environment Information**

```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: Linux 4.19 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 12.16.3 - /usr/sbin/node
    Yarn: 1.22.4 - /usr/sbin/yarn
    npm: 6.14.5 - /usr/sbin/npm

netlify-cli/2.51.0 linux-x64 node-v12.16.3

```
