### ISSUE TITLE
netlify-cli 2.52.0 and @netlify/build 1.0.5  Error: This plugin is missing a "manifest.yml"

### ISSUE THREAD

**Issue by moop-moop** [netlify/cli#928]
**- Do you want to request a _feature_ or report a _bug_?**
bug

**- What is the current behavior?**
```bash
┌─────────────────────────────┐                                                                 
│        Netlify Build        │                                                                 
└─────────────────────────────┘                                                                 
​                                                                                               
> Version                                                                                       
  @netlify/build 1.0.5                                                                          
​                                                                                               
> Flags                                                                                         
  mode: cli                                                                                     
​                                                                                               
> Current directory                                                                             
  C:\Users\***\GitHub\next-netlify-jest-testing                                                
​                                                                                               
> Config file                                                                                   
  C:\Users\***\GitHub\next-netlify-jest-testing\netlify.toml                                   
​                                                                                               
> Context                                                                                       
  production                                                                                    
​                                                                                               
┌─────────────────────────────────────────────────────────────────┐                             
│ Plugin "..\netlify-plugins\netlify-plugin-jest\" internal error │                             
└─────────────────────────────────────────────────────────────────┘                             
​                                                                                               
  Error message                                                                                 
  Error: This plugin is missing a "manifest.yml".                                               
  Please see the documentation at https://github.com/netlify/build#anatomy-of-a-plugin          
​                                                                                               
  Error location                                                                                
  While loading "..\netlify-plugins\netlify-plugin-jest\" from netlify.toml                     
      at async Promise.all (index 2)                                                            
      at async BuildCommand.run (/node_modules/netlify-cli/src/commands/build/index.js:16:21)   
      at async BuildCommand._run (/node_modules/@oclif/command/lib/command.js:43:20)            
      at async Config.runCommand (/node_modules/@oclif/config/lib/config.js:172:9)              
      at async Main.run (/node_modules/@oclif/command/lib/main.js:22:9)                         
```

**- If the current behavior is a bug, please provide the steps to reproduce.**
Trying to continue using a local path to develop a netlify build plugin that **does have a manifest.yml file.**

**manifest.yml**
```yaml
name: netlify-plugin-jest
inputs:
  - name: skipTests
    description: skip unit tests but leave the plugin present
    default: false
    required: true
  - name: skipStatusUpdate
    description: skip Github status update
    default: false
    required: true
  - name: testFailureErrorMessage
    description: string that exists inside of the error message that indicates tests failed
    default: Command failed with exit code 1
    required: true
```

**netlify.toml of referencing build**
```toml
[[plugins]]
package = "..\\netlify-plugins\\netlify-plugin-jest\\"

  [plugins.inputs]
  skipTests = true

[[plugins]]
package = "@netlify/plugin-local-install-core"
```

**- What is the expected behavior?**
It's expected the local netlify-build-plugin would load and function as it did in versions:
netlify-cli 2.51.0 and @netlify/build 0.4.47

**- Local Environment Information**

**worked**

```bash
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\GitHub\next-netlify-template\node_modules\.bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0

netlify-cli/2.51.0 win32-x64 node-v12.16.2
```

**now bugged**

```bash
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\GitHub\next-netlify-jest-testing\node_modules\.bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0

netlify-cli/2.52.0 win32-x64 node-v12.16.2
```
